FROM mhart/alpine-node

RUN apk update && apk upgrade && apk add --update build-base

# Create app directory
RUN mkdir -p /usr/src/app && echo "Tattva Git Logger"
COPY . /usr/src/app/
WORKDIR /usr/src/app
RUN npm install

WORKDIR /usr/src/app

# RUN rm ./data/CapitalOneJobs.json

CMD ["npm","start"]
