FROM mhart/alpine-node

# Create app directory
RUN mkdir -p /usr/src/app && echo "Tattva Git Logger"
COPY . /usr/src/app/
WORKDIR /usr/src/app
RUN npm install

WORKDIR /usr/src/app

# RUN rm ./data/CapitalOneJobs.json

CMD [ 'node', './runForAllOrgs.js', './data/testAllorgsFile.json' ]
